### ISSUE TITLE
Unable to configure TCPSink through App/web.config in case of using IP address

### ISSUE THREAD

**Issue by Wesam18** [pauldambra/Serilog.Sinks.Network#10]

**Comment by pauldambra** [comment]
Can you provide an example of your config?

**Comment by Wesam18** [comment]
I made a fix for it, I will make a pull request in a second :)

**Comment by Wesam18** [comment]
May you grant me permission to push a branch ?

**Comment by Wesam18** [comment]
Check pull request

**Comment by Wesam18** [comment]
## **Example configurations**
**Successful configuration**

    <add key="serilog:minimum-level" value="Verbose" />
    <add key="serilog:using:TCPSink" value="Serilog.Sinks.Network" />
    <add key="serilog:write-to:TCPSink.uri" value="someValidURL" />
    <add key="serilog:write-to:TCPSink.port" value="3251" />


** Unsuccessful configuration 

    <add key="serilog:minimum-level" value="Verbose" />
    <add key="serilog:using:TCPSink" value="Serilog.Sinks.Network" />
    <add key="serilog:write-to:TCPSink.uri" value="192.165.25.55" />
    <add key="serilog:write-to:TCPSink.port" value="3251" />

** OR **
    <add key="serilog:minimum-level" value="Verbose" />
    <add key="serilog:using:TCPSink" value="Serilog.Sinks.Network" />
    <add key="serilog:write-to:TCPSink.ipaddress" value="192.165.25.55" />
    <add key="serilog:write-to:TCPSink.port" value="3251" />

**Comment by pauldambra** [comment]
Ah, yeah, I only ever use host names in web config. Hadn't even occurred to me that breaks for other people! Good catch

**Comment by pauldambra** [comment]
Merged and released as https://www.nuget.org/packages/Serilog.Sinks.Network/1.0.3.35

**Comment by pauldambra** [comment]
Ah! what's the correct web.config format?

```
<add key="serilog:minimum-level" value="Verbose" />
<add key="serilog:using:TCPSink" value="Serilog.Sinks.Network" />
<add key="serilog:write-to:TCPSink.uri" value="192.165.25.55" />
<add key="serilog:write-to:TCPSink.port" value="3251" />
```

I'll update the README

**Comment by Wesam18** [comment]
yes, that is the correct on
