### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by agoretsky** [pauldambra/Serilog.Sinks.Network#15]
Currently it's not possible to reference this sink from .NET Core project. Any plans for .NET Standart support?

**Comment by pauldambra** [comment]
I don't have any plans yet, sorry. I've been waiting for the dust to settle around .Net core and friends.

Is it something you could have a stab at? Or are there other sinks that can be referenced that we could copy?

**Comment by JasonRowe** [comment]
I see this sink has support https://github.com/serilog/serilog-sinks-seq looks like me they went through the whole xproj to csproj fun. You get to skip all that fun and could just upgrade your csproj to the new tooling and start using dotnet.exe. Both of these changes would drastically simplify your build and project file.

Now would be a good time to get in as all the dust has settled with the tooling and dotnet core 2.0 is around the corner.

**Comment by rushi216** [comment]
Any updates on this?

**Comment by pauldambra** [comment]
It's still marked as 'help wanted'. I've no plans to update it _myself_ in the short term but anyone else is welcome to open a PR :)

**Comment by dolphy17** [comment]
I've created new PR for .Net Core support. Please review.
Help needed to fix the build.
#17

**Comment by pauldambra** [comment]
Awesome work @dolphy17! And thanks to @agoretsky for helping out too!

I'll close this and we can deal with any problems as new issues...
