### ISSUE TITLE
Invalid JSON generated by LogstashJsonFormatter when no properties on LogEvent

### ISSUE THREAD

**Issue by karlatkinson** [pauldambra/Serilog.Sinks.Network#18]
The LogstashJsonFormatter always appends a comma in the method WritePropertyAndValue.
This means if there are no items in the logEvent.Properties collection, then you end up with a trailing comma.
E.g.
```
{"timestamp":"2017-12-01T12:22:20.7748558+00:00","level":"Information","message":"My simple log message",}
```

**Comment by pauldambra** [comment]
Thanks for letting me know!

I can take a look at it this weekend (kids allowing :)) - happy to review a PR if you have time in the interim

**Comment by karlatkinson** [comment]
Cool. 👍 
I'm thinking the fix will be along the lines of this:
https://github.com/karlatkinson/Serilog.Sinks.Network/commit/60ed8b80663d8c41192b96b0f652573686bd3305
(sorry, VS has formatted the code so changes are a bit hidden).

Tried writing a failing test first though and seems like JSON.net annoyingly parses this happily :(
If you don't get round to it, i'll try and take a look next week.
