### ISSUE TITLE
Add publick key to the assembly

### ISSUE THREAD

**Issue by Ridlsan** [pauldambra/Serilog.Sinks.Network#19]
I'm working with Sharepoint and i need all dll's to have publickeytoken. Serilog has, every sink has except yours, It would be very helpful.
I need it only for 1.* version

**Comment by pauldambra** [comment]
Hey, 

can you point me at an example of one?

Thanks

**Comment by Ridlsan** [comment]
Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=**24c2f752a8e58a10**
Serilog.Sinks.Network, Version=1.2.0.48, Culture=neutral, PublicKeyToken=**null**
Yours publick key is null. U should create key.snk and sign dll
Just make this in studio. Dont set password, its not needed. And thats all, thank you
![default](https://user-images.githubusercontent.com/13232749/35501220-5ff67a4c-04ea-11e8-8692-36dfe7e26668.png)

**Comment by Ridlsan** [comment]
@pauldambra any progress?

**Comment by pauldambra** [comment]
I don't use visual studio so genuinely don't know how to go about it. 

I've also only heard bad things about signed assemblies...

Can you point me at where in one of the other sinks they've implemented it so I can see how it is done without a GUI?

**Comment by pauldambra** [comment]
I would say I'm open to a PR but I'd need to generate and own a key so...

**Comment by Ridlsan** [comment]
I can make PR for u but dont understand how to get 1.* version. 
Or just put this in csproj file: 
```
 <SignAssembly>true</SignAssembly>
<AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
<DelaySign>false</DelaySign>
```

And attach this key.snk i've generated for u. It is not encrypted, so no one owns it

![default](https://user-images.githubusercontent.com/13232749/35634711-64dfd54c-06bd-11e8-9b27-a3d1a11bdeda.png)

[key.zip](https://github.com/pauldambra/Serilog.Sinks.Network/files/1682435/key.zip)

If u want example. Look for example in [Console sink](https://github.com/serilog/serilog-sinks-console/blob/dev/src/Serilog.Sinks.Console/Serilog.Sinks.Console.csproj) project file.

u can find snk file in [asserts folder](https://github.com/serilog/serilog-sinks-console/tree/dev/assets)

**Comment by pauldambra** [comment]
So, the next question would be whether adding a key to 1.x breaks it for
anyone currently using 1.x?

I'd expect so... in which case it's not a change we can make to 1.x and
we'd need to find another solution

(sorry, not trying to be difficult I've never had to deal with signed
assemblies so just being careful)

**Comment by Ridlsan** [comment]
@pauldambra it will not break anything. When they update it from nuget all links will be updated and they will not even know about it

**Comment by Ridlsan** [comment]
@pauldambra yeah, it can be solution, but i can also make fork of ur project and make signed nuget package. So, can u tell me, which branch is 1x version or what commit ?

**Comment by pauldambra** [comment]
True, it's open source for a reason :)

NB it's apache licensed so you need to maintain that. I would say that you're then in the position of maintaining and updating your branch if you need to pull in changes so it feels like the harder route for you but YMMV. 

The last 1.x.x commit was e40ef23b20a8da12aed65d258c548dcb70e71e10

**Comment by Ridlsan** [comment]
Ok! Thanks
