### ISSUE TITLE
Recommend a good tcp/udp listener for windows

### ISSUE THREAD

**Issue by smurfster** [pauldambra/Serilog.Sinks.Network#20]
Hi,

Just wondering what tools you would use this serilog extension with in order to see the logs

Cheers

**Comment by pauldambra** [comment]
This was written with logstash and the elastic stack in mind. So while it
doesn't require those to be present, it just sends JSON over the network, I
don't know if usage without them.

Does that help? Do feel free to ask follow up questions...

**Comment by pauldambra** [comment]
Ah, just seen the title...

It's been a while since I've used windows. For Dev work I've used wireshark to see network traffic.... I'd that wear you mean?

**Comment by pauldambra** [comment]
Was writing the other comments while I was out and about...

You can get ELK running locally using https://www.elastic.co/blog/a-full-stack-in-one-command. If you're interested in seeing why you might want to log using this sink that's probably the best way.

If you're only interested in seeing what is being sent for debug (or similar) purposes you can use https://www.wireshark.org/ or https://www.charlesproxy.com/ (lots of people have recommended charles to me but I haven't used it).

As I said earlier if I've misunderstood or you still want to know more just let me know

**Comment by pauldambra** [comment]
I'll close this but do feel free to ask further questions if you have them. I'm on twitter @pauldambra too if you want to chat there
